version: '3'

services:

  triumphapp:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
#    ports:
#      - "8080:8000"
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=triumph_db
      - SQL_USER=triumph_user
      - SQL_PASSWORD=bhbyf,fkfuekf
      - SQL_HOST=database
      - SQL_PORT=5432
      - DATABASE=postgres
    volumes:
      - ./src:/usr/src/app/triumph
      - static_volume:/usr/src/app/triumph/triumph/static  # <-- bind the static volume
      - media_volume:/usr/src/app/triumph/triumph/media  # <-- bind the media volume
    networks:
      - nginx_network
      - database_network
    depends_on:
      - database

  nginx:
    image: nginx:1.13
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/triumph/triumph/static  # <-- bind the static volume
      - media_volume:/usr/src/app/triumph/triumph/media  # <-- bind the media volume

    depends_on:
      - triumphapp
    networks:
      - nginx_network


  database:
    image: postgres:9.5
#    env_file:
#      - config/db/database1_env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=bhbyf,fkfuekf
      - POSTGRES_USER=triumph_user
      - POSTGRES_DB=triumph_db
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data


networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media
