# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 17:36
from __future__ import unicode_literals

import ckeditor.fields
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=core.utils.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'ordering': ['-date_created', '-date_updated'],
            },
        ),
    ]
