# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170113_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='ExampleNonUploadModel',
        ),
    ]
