# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170121_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content2',
        ),
    ]
