# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('rest_days', models.ManyToManyField(related_name='rest_schedule', to='timetable.Days', verbose_name='Выходные дни')),
                ('work_days', models.ManyToManyField(related_name='work_schedule', to='timetable.Days', verbose_name='Рабочие дни')),
            ],
        ),
    ]
