# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Расписание'},
        ),
        migrations.RenameField(
            model_name='days',
            old_name='day',
            new_name='title',
        ),
    ]
