# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_info',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
