# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20170818_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timetable.Schedule', verbose_name='Расписание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='timetable.Room', verbose_name='Комната'),
        ),
    ]
