# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20170730_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 7, 30, 20, 19, 35, 593290), verbose_name='Конец занятий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 7, 30, 20, 19, 51, 428801), verbose_name='Начало занятий'),
            preserve_default=False,
        ),
    ]
