# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-03 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20170818_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_info',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
