# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20170730_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('finish', models.TimeField(verbose_name='Конец')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Days', verbose_name='День')),
            ],
            options={
                'verbose_name_plural': 'Занятие',
            },
        ),
    ]
