# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.ManyToManyField(to='timetable.Days', verbose_name='День'),
        ),
    ]
