# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_school_promo'),
        ('timetable', '0006_auto_20170812_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Coach', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.TimeField(verbose_name='Конец занятий'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.TimeField(verbose_name='Начало занятий'),
        ),
    ]
