# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20170812_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_info',
            field=models.CharField(default=datetime.datetime(2017, 8, 12, 21, 57, 14, 415901), max_length=255, verbose_name='Дополнительная информация'),
            preserve_default=False,
        ),
    ]
