# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20170812_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#EF5350', 'красный'), ('#AB47BC', 'фиолетовый'), ('#7E57C2', 'глубоко фиолетовый'), ('#5C6BC0', 'индиго'), ('#42A5F5', 'голубой'), ('#29B6F6', 'легко-голубой'), ('#26C6DA', 'циан'), ('#66BB6A', 'бирюзовый'), ('#9CCC65', 'зеленый'), ('#D4E157', 'лайм'), ('#FFEE58', 'желтый'), ('#FFCA28', 'янтарный'), ('#FFA726', 'оранжевый'), ('#FF7043', 'глубоко оранжевый'), ('#8D6E63', 'желтый'), ('#8D6E63', 'коричневый'), ('#78909C', 'серый')], default='#EF5350', max_length=15, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
