# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Школа спортивного танца «Триумф»', max_length=200, verbose_name='Титул')),
                ('h1', models.CharField(default='Школа спортивного танца «Триумф»', max_length=200, verbose_name='Заголовок первого уровня')),
                ('key_words', models.TextField(default="школа танцев, клуб танцев, харьков, в харькове, харьковская, триумф, ирина балагула, контемн, детский танец, танцы для детей, бальные танцы, хип-хоп, политех, хпи, НТУ 'ХПИ'", verbose_name='Ключевые слова')),
                ('description', models.TextField(default='Школа спортивного танца «Триумф» — известная школа танцев в Харькове. Танцы для каждого. Широкое расписание. Профессиональные преподаватели. Удобное расположение в центре города. Звоните и присоеденяйтесь! (067)256-54-26. С танцем по жизни!', verbose_name='Описание')),
            ],
        ),
    ]
