# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-14 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_auto_20180614_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name_plural': 'SEO'},
        ),
    ]
