# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-30 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_auto_20180614_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEO',
        ),
    ]
