# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('video', embed_video.fields.EmbedVideoField(help_text='Можно добавить видео с YouTube, Soundcloud или Vimeo', verbose_name='Ссылка на видеоролик')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Видеогалерия',
                'ordering': ['-date_created', '-date_updated'],
            },
        ),
    ]
