# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 23:36
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20170110_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(help_text='Можно добавить видео с YouTube, Soundcloud или Vimeo', verbose_name='Ссылка на видеоролик'),
        ),
    ]
