# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 19:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2017, 1, 21, 19, 45, 52, 660817)),
            preserve_default=False,
        ),
    ]
