# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 18:34
from __future__ import unicode_literals

import ckeditor.fields
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=core.utils.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('is_cover_photo', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Танцевальные направления',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.Style'),
        ),
    ]
