# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='style',
            name='image',
        ),
        migrations.RemoveField(
            model_name='style',
            name='width_field',
        ),
    ]
