# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-30 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0002_auto_20180630_1206'),
        ('styles', '0002_auto_20180614_1223'),
    ]

    operations = [
    ]
