# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-14 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0004_auto_20180630_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='subtitle',
            field=models.CharField(default=datetime.datetime(2018, 8, 14, 11, 37, 40, 556702), max_length=500, verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
    ]
