# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0006_auto_20180814_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Группа'),
        ),
    ]
