# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0008_auto_20180821_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='sub_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='styles.Style'),
        ),
    ]
