# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-07 11:36
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0009_style_sub_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_location, verbose_name='Промо фотография'),
        ),
        migrations.AlterField(
            model_name='style',
            name='sub_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='styles.Style', verbose_name='Родительский стиль'),
        ),
    ]
