# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0010_auto_20180907_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Группа'),
        ),
    ]
