# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 12:07
from __future__ import unicode_literals

import ckeditor.fields
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('avatar', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=core.utils.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('title', ckeditor.fields.RichTextField()),
                ('quote', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
