# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20170109_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_cover_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=240, null=True, verbose_name='Название'),
        ),
    ]
