# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_auto_20170109_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
