# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 17:19
from __future__ import unicode_literals

import ckeditor.fields
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('avatar', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=core.utils.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('title', ckeditor.fields.RichTextField()),
                ('quote', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Тренеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('phones', models.CharField(max_length=255, verbose_name='Телефоны')),
                ('work_time', models.CharField(max_length=255, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='DanceHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Танцевальный зал',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=core.utils.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('dance_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.DanceHall')),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=core.utils.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Труимф', max_length=60, verbose_name='Название')),
                ('about', ckeditor.fields.RichTextField()),
                ('promo', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Школа',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AddField(
            model_name='dancehall',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hall', to='school.School'),
        ),
        migrations.AddField(
            model_name='contact',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='school.School'),
        ),
        migrations.AddField(
            model_name='coach',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
