# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 22:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Труимф', max_length=60, verbose_name='Школа')),
                ('about', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Школа',
            },
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['id'], 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AddField(
            model_name='coach',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
