# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 14:48
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170130_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=core.utils.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
