# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-30 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_merge_20180630_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='browser_title',
            field=models.CharField(default='Школа спортивного танца «Триумф»', max_length=200, null=True, verbose_name='Заголовок в браузере'),
        ),
        migrations.AddField(
            model_name='school',
            name='h1',
            field=models.CharField(default='Школа спортивного танца «Триумф»', max_length=200, null=True, verbose_name='Заголовок первого уровня'),
        ),
        migrations.AddField(
            model_name='school',
            name='head_description',
            field=models.TextField(default='Школа спортивного танца «Триумф» — известная школа танцев в Харькове. Танцы для каждого. Широкое расписание. Профессиональные преподаватели. Удобное расположение в центре города. Звоните и присоеденяйтесь! (067)256-54-26. С танцем по жизни!', null=True, verbose_name='Описание для метатега'),
        ),
        migrations.AddField(
            model_name='school',
            name='key_words',
            field=models.TextField(default="школа танцев, клуб танцев, харьков, в харькове, харьковская, триумф, ирина балагула, контемн, детский танец, танцы для детей, бальные танцы, хип-хоп, политех, хпи, НТУ 'ХПИ'", null=True, verbose_name='Ключевые слова'),
        ),
    ]
