# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20170212_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DanceHallPhoto',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='dancehall',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hall', to='school.School'),
        ),
    ]
