# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20180812_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default=12, max_length=255, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='postcode',
            field=models.CharField(default=datetime.datetime(2018, 8, 13, 9, 42, 6, 653773), max_length=255, verbose_name='Почтовый индекс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
