# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='promo',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
