# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 16:49
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attainments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attainments',
            name='intro',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2017, 5, 12, 16, 49, 51, 924836)),
            preserve_default=False,
        ),
    ]
